# Generated by Django 2.2.28 on 2024-03-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSpending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Electric bill', 'Electric Bills'), ('Water bill', 'Water Bills'), ('Groceries', 'Groceries'), ('Assets', 'Assets'), ('Cleanliness', 'Cleanliness'), ('Intenet', 'Internet'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Others', 'Others')], max_length=128)),
                ('amount', models.IntegerField()),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_manager.FinancialAccount')),
            ],
            options={
                'unique_together': {('financial_account', 'category')},
            },
        ),
    ]
