# Generated by Django 4.2.9 on 2024-03-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
    ]
