# Generated by Django 2.2.28 on 2024-03-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0002_auto_20240321_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name',
        ),
    ]
