# Generated by Django 4.2.9 on 2024-03-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0002_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(),
        ),
    ]
