# Generated by Django 5.0.3 on 2024-03-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0002_auto_20240321_2232'),
        ('finance_manager', '0002_newspending'),
    ]

    operations = [
    ]
