# Generated by Django 2.2.28 on 2024-03-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0002_newspending'),
        ('finance_manager', '0003_auto_20240322_0046'),
    ]

    operations = [
    ]
