# Generated by Django 4.2.9 on 2024-03-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0003_alter_budget_amount_alter_expense_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
