# Generated by Django 2.2.28 on 2024-03-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0003_merge_0002_auto_20240321_2232_0002_newspending'),
        ('finance_manager', '0004_merge_20240322_0623'),
    ]

    operations = [
    ]
