# Generated by Django 4.2.9 on 2024-03-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0004_alter_expense_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newspending',
            unique_together=set(),
        ),
    ]
